"""baseline_schema

Revision ID: 603bbc60c42b
Revises: 
Create Date: 2026-06-19 11:37:26.693149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '603bbc60c42b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='plantier'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', 'TXT', 'MD', name='filetype'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('semantic_drift_score', sa.Float(), nullable=True),
    sa.Column('factual_drift_score', sa.Float(), nullable=True),
    sa.Column('aligned_claims', sa.Integer(), nullable=True),
    sa.Column('drift_type', sa.String(length=50), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('supersedes_document_id', sa.UUID(), nullable=True),
    sa.Column('authority_level', sa.Integer(), nullable=True),
    sa.Column('owner_department', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PARTIAL', 'FAILED', 'COMPLETE', name='processingstatus'), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supersedes_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index('ix_documents_org_created', 'documents', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_documents_org_drift', 'documents', ['org_id', 'drift_score'], unique=False)
    op.create_index('ix_documents_org_hash', 'documents', ['org_id', 'content_hash'], unique=False)
    op.create_table('org_drift_weights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('density_weight', sa.Float(), nullable=True),
    sa.Column('confidence_weight', sa.Float(), nullable=True),
    sa.Column('volume_weight', sa.Float(), nullable=True),
    sa.Column('factual_weight', sa.Float(), nullable=True),
    sa.Column('semantic_weight', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('embedding_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_document', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_search_vector', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('CONTRADICTION', 'SEMANTIC_DRIFT', 'STALE_CONTENT', 'MISSING_REFERENCE', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('source_doc_id', sa.UUID(), nullable=True),
    sa.Column('target_doc_id', sa.UUID(), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('target_chunk_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['target_chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['target_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_org_status_severity', 'alerts', ['org_id', 'status', 'severity'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_sentence', sa.Text(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('predicate', sa.String(length=512), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modality', sa.Enum('MANDATORY', 'OPTIONAL', 'PROHIBITED', 'RECOMMENDED', 'INFORMATIONAL', name='claimmodality'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_content_hash', 'claims', ['content_hash'], unique=False)
    op.create_index('ix_claims_document_id', 'claims', ['document_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_org_name', 'entities', ['org_id', 'name'], unique=False)
    op.create_table('contradiction_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('chunk_a_id', sa.UUID(), nullable=False),
    sa.Column('chunk_b_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Enum('CONSISTENT', 'CONTRADICTORY', 'SUPERSEDES', 'UNRELATED', 'EVOLUTION', name='contradictionclassification'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('conflicting_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aligned_claims_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FALSE_POSITIVE', 'INTENTIONAL_DIVERGENCE', name='reviewstatus'), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('is_temporal_evolution', sa.Boolean(), nullable=True),
    sa.Column('sampled', sa.Boolean(), nullable=True),
    sa.Column('gate_similarity', sa.Float(), nullable=True),
    sa.Column('inferred_lineage', sa.Boolean(), nullable=True),
    sa.Column('explanation_valid', sa.Boolean(), nullable=True),
    sa.Column('contradiction_type', sa.String(length=50), nullable=True),
    sa.Column('scan_path', sa.String(length=20), nullable=True),
    sa.Column('claim_a_id', sa.UUID(), nullable=True),
    sa.Column('claim_b_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('claim_a_id < claim_b_id', name='ck_contradiction_claim_order'),
    sa.ForeignKeyConstraint(['chunk_a_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['chunk_b_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_a_id', 'claim_b_id', name='uq_contradiction_claim_pair')
    )
    op.create_index('ix_contradiction_claim_pair', 'contradiction_pairs', ['claim_a_id', 'claim_b_id'], unique=False)
    op.create_table('relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=255), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heuristic_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pair_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title_similarity_score', sa.Float(), nullable=True),
    sa.Column('date_gap_days', sa.Integer(), nullable=True),
    sa.Column('department_match', sa.Boolean(), nullable=True),
    sa.Column('reviewer_decision', sa.String(length=50), nullable=False),
    sa.Column('original_classification', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pair_id'], ['contradiction_pairs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heuristic_feedback_org', 'heuristic_feedback', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_heuristic_feedback_org', table_name='heuristic_feedback')
    op.drop_table('heuristic_feedback')
    op.drop_table('relations')
    op.drop_index('ix_contradiction_claim_pair', table_name='contradiction_pairs')
    op.drop_table('contradiction_pairs')
    op.drop_index('ix_entities_org_name', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_claims_document_id', table_name='claims')
    op.drop_index('ix_claims_content_hash', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_alerts_org_status_severity', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_chunks_search_vector', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_document', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('org_drift_weights')
    op.drop_index('ix_documents_org_hash', table_name='documents')
    op.drop_index('ix_documents_org_drift', table_name='documents')
    op.drop_index('ix_documents_org_created', table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
