// AUTO-GENERATED demo fixtures — a snapshot of the seeded "KnowledgeDrift Demo"
// org (3 Urban Mobility policy docs) captured from the real backend. Used by the
// API client when NEXT_PUBLIC_DEMO_MODE=true so the frontend is fully interactive
// on Vercel with no backend. Regenerate by re-capturing the live endpoints.
/* eslint-disable */
export const DEMO_DATA = {
  "me": {
    "id": "f9abb4be-d4b3-4df1-84d2-2264f29412e4",
    "email": "admin@knowledgedrift.dev",
    "full_name": "Demo Admin",
    "org_id": "4adf3dd5-e58f-465f-89fa-e235f9b9e9eb",
    "role": "ADMIN",
    "is_active": true
  },
  "documents": {
    "documents": [
      {
        "id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "title": "Urban Mobility Policy \u2014 Interim Compromise",
        "filename": "Urban Mobility Policy \u2014 Interim Compromise.txt",
        "file_type": "txt",
        "file_size": 1122,
        "page_count": 1,
        "drift_score": 66.65,
        "semantic_drift_score": 20.21,
        "factual_drift_score": 97.61,
        "drift_type": "both",
        "is_processed": true,
        "created_at": "2026-06-19T08:31:47.951281Z"
      },
      {
        "id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "filename": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint.txt",
        "file_type": "txt",
        "file_size": 1119,
        "page_count": 1,
        "drift_score": 66.63,
        "semantic_drift_score": 20.21,
        "factual_drift_score": 97.58,
        "drift_type": "both",
        "is_processed": true,
        "created_at": "2026-06-19T08:31:38.820598Z"
      },
      {
        "id": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "filename": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification.txt",
        "file_type": "txt",
        "file_size": 1123,
        "page_count": 1,
        "drift_score": 66.67,
        "semantic_drift_score": 20.21,
        "factual_drift_score": 97.65,
        "drift_type": "both",
        "is_processed": true,
        "created_at": "2026-06-19T08:31:29.395640Z"
      }
    ],
    "total": 3
  },
  "drift": {
    "scores": [
      {
        "document_id": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "drift_score": 66.67,
        "semantic_drift_score": 20.21,
        "factual_drift_score": 97.65,
        "drift_type": "both",
        "contradiction_count": 0,
        "contradiction_examples": [],
        "factors": {}
      },
      {
        "document_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "title": "Urban Mobility Policy \u2014 Interim Compromise",
        "drift_score": 66.65,
        "semantic_drift_score": 20.21,
        "factual_drift_score": 97.61,
        "drift_type": "both",
        "contradiction_count": 0,
        "contradiction_examples": [],
        "factors": {}
      },
      {
        "document_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "drift_score": 66.63,
        "semantic_drift_score": 20.21,
        "factual_drift_score": 97.58,
        "drift_type": "both",
        "contradiction_count": 0,
        "contradiction_examples": [],
        "factors": {}
      }
    ]
  },
  "graph": {
    "nodes": [
      {
        "id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "name": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "type": "DOCUMENT",
        "label": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "drift_score": 66.63,
        "factual_drift": 97.58,
        "semantic_drift": 20.21
      },
      {
        "id": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "name": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "type": "DOCUMENT",
        "label": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "drift_score": 66.67,
        "factual_drift": 97.65,
        "semantic_drift": 20.21
      },
      {
        "id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "name": "Urban Mobility Policy \u2014 Interim Compromise",
        "type": "DOCUMENT",
        "label": "Urban Mobility Policy \u2014 Interim Compromise",
        "drift_score": 66.65,
        "factual_drift": 97.61,
        "semantic_drift": 20.21
      }
    ],
    "links": [
      {
        "source": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "target": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "relation": "CONTRADICTS",
        "confidence": 0.9996,
        "weight": 12,
        "avg_confidence": 0.9959,
        "types": {}
      },
      {
        "source": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "relation": "CONTRADICTS",
        "confidence": 0.9994,
        "weight": 10,
        "avg_confidence": 0.9979,
        "types": {}
      },
      {
        "source": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "target": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "relation": "CONTRADICTS",
        "confidence": 0.9995,
        "weight": 10,
        "avg_confidence": 0.9933,
        "types": {}
      }
    ]
  },
  "alerts": {
    "alerts": [
      {
        "id": "95ba9359-bef5-4e62-a8a3-c48cbb4c144b",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "description": "These two statements present conflicting information. Contradiction detected with 98% confidence.",
        "evidence": {
          "claim_a": "The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter.",
          "claim_b": "The transit authority will operate weekend night service for 24 hours.",
          "confidence": 0.9779109358787537,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "target_doc_id": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "2de330d3-3810-4f0c-80f3-1293cc441bc7",
        "created_at": "2026-06-20T05:59:55.715678Z"
      },
      {
        "id": "199b2284-aaad-4028-b554-711f8a74e3ba",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "description": "These two statements present conflicting information. Contradiction detected with 99% confidence.",
        "evidence": {
          "claim_a": "The transit authority will provide an annual operating subsidy of 50 million dollars.",
          "claim_b": "The transit authority will allocate 500 million dollars for eastern corridor infrastructure upgrades.",
          "confidence": 0.986403226852417,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "target_doc_id": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "2de330d3-3810-4f0c-80f3-1293cc441bc7",
        "created_at": "2026-06-19T08:33:39.765152Z"
      },
      {
        "id": "1d8a9ba1-8844-4327-b5c3-8d7e326fb014",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will provide an annual operating subsidy of 120 million dollars.",
          "claim_b": "The transit authority will provide an annual operating subsidy of 50 million dollars.",
          "confidence": 0.9995033740997314,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "target_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "created_at": "2026-06-19T08:32:27.072406Z"
      },
      {
        "id": "ff6e7356-0300-49ef-b29c-bbfc36611dc7",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will operate weekend night service for 16 hours.",
          "claim_b": "The transit authority will operate weekend night service for 6 hours.",
          "confidence": 0.9990457892417908,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "target_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "created_at": "2026-06-19T08:32:27.069651Z"
      },
      {
        "id": "4cb621f2-ab47-4070-bc07-08bf27a3a2fe",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will reduce transit carbon emissions by 35 percent.",
          "claim_b": "The transit authority will reduce transit carbon emissions by 10 percent.",
          "confidence": 0.9988563060760498,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "created_at": "2026-06-19T08:32:27.067925Z"
      },
      {
        "id": "59f9e4cd-d986-449d-b7bf-0bc72ecb542a",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will set the base passenger fare at 3 dollars per ride.",
          "claim_b": "The transit authority will set the base passenger fare at 5 dollars per ride.",
          "confidence": 0.9988592863082886,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "created_at": "2026-06-19T08:32:27.066154Z"
      },
      {
        "id": "b1eb44bd-65fc-4de8-b0c5-9eedbc51f2f7",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will provide 3500 new park-and-ride parking spaces.",
          "claim_b": "The transit authority will provide 1000 new park-and-ride parking spaces.",
          "confidence": 0.9989352822303772,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "created_at": "2026-06-19T08:32:27.064519Z"
      },
      {
        "id": "4e319873-4bb5-41d2-b02e-65013ae73e61",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will operate 2800 electric buses across the network.",
          "claim_b": "The transit authority will operate 1500 electric buses across the network.",
          "confidence": 0.9977397918701172,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "target_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "created_at": "2026-06-19T08:32:27.062969Z"
      },
      {
        "id": "e2194b6f-1048-4e6f-aa49-dbc000341f79",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will expand the dedicated bus lane network to 150 kilometers.",
          "claim_b": "The transit authority will expand the dedicated bus lane network to 50 kilometers.",
          "confidence": 0.9994169473648071,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "created_at": "2026-06-19T08:32:27.061257Z"
      },
      {
        "id": "20016a95-69e0-4c44-bec6-13bb5636991b",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will allocate 320 million dollars for eastern corridor infrastructure upgrades.",
          "claim_b": "The transit authority will allocate 180 million dollars for eastern corridor infrastructure upgrades.",
          "confidence": 0.998656153678894,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "target_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "created_at": "2026-06-19T08:32:27.059334Z"
      },
      {
        "id": "5a4a3730-d656-49ec-b966-c30733cebc7b",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "evidence": {
          "claim_a": "The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter.",
          "claim_b": "The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter.",
          "confidence": 0.9963846206665039,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "created_at": "2026-06-19T08:32:27.056734Z"
      },
      {
        "id": "ff102f8a-7588-427e-947f-3b72681f1d8b",
        "alert_type": "contradiction",
        "severity": "high",
        "title": "Contradiction detected in Urban Mobility Policy \u2014 Interim Compromise",
        "description": "These two statements present conflicting information. Contradiction detected with 95% confidence.",
        "evidence": {
          "claim_a": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months.",
          "claim_b": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months.",
          "confidence": 0.9453384280204773,
          "confidence_band": "high",
          "requires_review": false,
          "temporal_reason": "",
          "is_temporal_evolution": false
        },
        "status": "open",
        "source_doc_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "target_doc_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "source_chunk_id": "7c96ebba-2923-4f8a-80ad-d14d706a7082",
        "target_chunk_id": "1b358cc1-1bac-4291-87e1-e8f2a182400d",
        "created_at": "2026-06-19T08:32:26.478907Z"
      }
    ],
    "total": 32
  },
  "alertStats": {
    "total": 32,
    "open": 32,
    "critical": 0,
    "high": 32,
    "resolved_today": 0
  },
  "reviews": {
    "items": [
      {
        "id": "5650029f-020c-4f55-ad89-1cbc252c3c20",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9779109358787537,
        "explanation": "These two statements present conflicting information. Contradiction detected with 98% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": true,
        "gate_similarity": 0.5044530060570774,
        "created_at": "2026-06-20T05:59:55.734511+00:00"
      },
      {
        "id": "40f5ad2c-88d3-4093-a813-16292856f8b2",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.986403226852417,
        "explanation": "These two statements present conflicting information. Contradiction detected with 99% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": true,
        "gate_similarity": 0.6504416026708096,
        "created_at": "2026-06-19T08:33:39.771084+00:00"
      },
      {
        "id": "06e3dc50-edc7-4750-a36f-06573f61da58",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9995033740997314,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.912565626318933,
        "created_at": "2026-06-19T08:32:27.072981+00:00"
      },
      {
        "id": "ef2dcf68-6b50-4ef5-9cbc-36d5c8d46c4b",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9990457892417908,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9208328791174976,
        "created_at": "2026-06-19T08:32:27.071232+00:00"
      },
      {
        "id": "61a20c20-2d1f-43cd-9bc1-1529ea9dadd8",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9988563060760498,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.925641437947133,
        "created_at": "2026-06-19T08:32:27.068355+00:00"
      },
      {
        "id": "935fbfa4-1898-4eaa-83e1-e9aa58b9a822",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9988592863082886,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.8674333263570285,
        "created_at": "2026-06-19T08:32:27.066539+00:00"
      },
      {
        "id": "976db047-c730-435c-9c87-b53a5007e867",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9989352822303772,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9271120509551429,
        "created_at": "2026-06-19T08:32:27.064951+00:00"
      },
      {
        "id": "5bd49f03-345d-4262-a58e-eae1efd4ea0a",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9977397918701172,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.8731724522648633,
        "created_at": "2026-06-19T08:32:27.063364+00:00"
      },
      {
        "id": "8337513a-7ab7-4af7-a9fb-194e75cdbd69",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9994169473648071,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9579115203009696,
        "created_at": "2026-06-19T08:32:27.061688+00:00"
      },
      {
        "id": "92765189-8089-496e-bb87-86389080a844",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.998656153678894,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9593160219608231,
        "created_at": "2026-06-19T08:32:27.059865+00:00"
      },
      {
        "id": "b23bfa7c-373d-438c-8508-9814bea4037a",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9963846206665039,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9510011392263177,
        "created_at": "2026-06-19T08:32:27.057620+00:00"
      },
      {
        "id": "e4a16ac9-7884-4877-a56b-2930434b7723",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9453384280204773,
        "explanation": "These two statements present conflicting information. Contradiction detected with 95% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9778181773282547,
        "created_at": "2026-06-19T08:32:26.484227+00:00"
      },
      {
        "id": "3960ed14-4204-49b8-8771-6887eef49f82",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9988717436790466,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9468201580928356,
        "created_at": "2026-06-19T08:31:49.527595+00:00"
      },
      {
        "id": "c95dcb96-39c3-4159-b2b8-cf7d3e2636de",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9982118606567383,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9280506699345916,
        "created_at": "2026-06-19T08:31:49.526019+00:00"
      },
      {
        "id": "c88f1348-74c7-46e8-86f7-c5a4004f9361",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9993504881858826,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9395370797658337,
        "created_at": "2026-06-19T08:31:49.524395+00:00"
      },
      {
        "id": "33869b2f-025b-429a-ba39-160eb89befeb",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9991082549095154,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.8987084216759327,
        "created_at": "2026-06-19T08:31:49.522855+00:00"
      },
      {
        "id": "b5a10626-eb2a-4345-8464-409cd4bf7f2e",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9977455735206604,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.8785503142401349,
        "created_at": "2026-06-19T08:31:49.521063+00:00"
      },
      {
        "id": "52a26132-d661-41c2-a445-33058f71cbbb",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9972049593925476,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9132440212970391,
        "created_at": "2026-06-19T08:31:49.519220+00:00"
      },
      {
        "id": "73dbd8bd-8737-4bfc-841c-7db38be3e4ef",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9980872273445129,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9754029366021306,
        "created_at": "2026-06-19T08:31:49.517479+00:00"
      },
      {
        "id": "045ce587-b0e8-4c8c-8241-3f08c165bca3",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9971375465393066,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.955951507407107,
        "created_at": "2026-06-19T08:31:49.515907+00:00"
      },
      {
        "id": "3257827a-f7f6-4149-9515-1b4cd4420dd4",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.998955249786377,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9642922117887057,
        "created_at": "2026-06-19T08:31:49.514286+00:00"
      },
      {
        "id": "a2b1d5a7-2a67-47b0-b75a-220f42bb2549",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "classification": "contradictory",
        "confidence": 0.9946334362030029,
        "explanation": "These two statements present conflicting information. Contradiction detected with 99% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": true,
        "sampled": false,
        "gate_similarity": 0.9904919066718941,
        "created_at": "2026-06-19T08:31:49.512137+00:00"
      },
      {
        "id": "5fd2dc08-a326-4e1e-bc5d-aaee1d726b98",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9995635151863098,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.91387645118996,
        "created_at": "2026-06-19T08:31:42.014984+00:00"
      },
      {
        "id": "70271ff6-a32d-4827-b353-8b92d7bd8e54",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9992832541465759,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9316639352641539,
        "created_at": "2026-06-19T08:31:42.012050+00:00"
      },
      {
        "id": "32dc9d35-636f-4799-bf46-9d6647372cc5",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9991324543952942,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9296747431635173,
        "created_at": "2026-06-19T08:31:42.009103+00:00"
      },
      {
        "id": "167eb398-973b-4590-8b0f-f38613271a93",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9991699457168579,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.8970376879752685,
        "created_at": "2026-06-19T08:31:42.005981+00:00"
      },
      {
        "id": "cb9be770-c3d2-458b-bbb1-8b666ae28676",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9974724650382996,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9416367429899511,
        "created_at": "2026-06-19T08:31:42.003152+00:00"
      },
      {
        "id": "afc99b33-9609-47c5-be72-bd0f835299aa",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9965282082557678,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9142459273148688,
        "created_at": "2026-06-19T08:31:41.998803+00:00"
      },
      {
        "id": "d2bce55e-f23c-48b2-aeed-0bad77853fcd",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9991863369941711,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9460563691189094,
        "created_at": "2026-06-19T08:31:41.994271+00:00"
      },
      {
        "id": "1964b09f-de49-4d81-ba9b-c4cb60e5e59f",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "doc_b_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "classification": "contradictory",
        "confidence": 0.9995212554931641,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9611947553437741,
        "created_at": "2026-06-19T08:31:41.990874+00:00"
      },
      {
        "id": "4ed80d55-e2af-4159-ba8f-f1830e725da3",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9991884827613831,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9594735040813499,
        "created_at": "2026-06-19T08:31:41.987959+00:00"
      },
      {
        "id": "f8793a45-04a7-47e4-a7f5-3a687ca33a33",
        "chunk_a_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastruc",
        "chunk_b_text": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastruc",
        "doc_a_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "doc_b_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "classification": "contradictory",
        "confidence": 0.9979800581932068,
        "explanation": "These two statements present conflicting information. Contradiction detected with 100% confidence.",
        "review_status": "PENDING",
        "reviewed_by": null,
        "reviewed_at": null,
        "review_reason": null,
        "is_temporal_evolution": false,
        "inferred_lineage": false,
        "explanation_valid": false,
        "sampled": false,
        "gate_similarity": 0.9785719265515485,
        "created_at": "2026-06-19T08:31:41.984433+00:00"
      }
    ],
    "total": 32,
    "limit": 50,
    "offset": 0
  },
  "reviewStats": {
    "total_pairs": 32,
    "reviewed": 0,
    "pending": 32,
    "approved": 0,
    "rejected": 0,
    "false_positive": 0,
    "intentional_divergence": 0,
    "temporal_evolutions": 0,
    "review_rate": 0.0
  },
  "gateCalibration": {
    "current_threshold": 0.75,
    "sample_rate": 0.05,
    "total_sampled_pairs": 2,
    "total_above_threshold_pairs": 30,
    "sampled_contradictions": 2,
    "sampled_contradiction_rate": 1.0,
    "sampled_similarity": {
      "avg": 0.5774,
      "min": 0.5045,
      "max": 0.6504
    },
    "above_threshold_similarity": {
      "avg": 0.9346,
      "min": 0.8674
    },
    "recommendation": {
      "action": "LOWER_THRESHOLD",
      "suggested_threshold": 0.75,
      "reason": "100.0% of sampled below-threshold pairs are real contradictions \u2014 threshold may be too aggressive"
    }
  },
  "lineageStats": {
    "total_inferred_evolutions": 0,
    "total_reviewed": 0,
    "overrides": 0,
    "confirmations": 0,
    "override_rate": 0.0,
    "overridden_signals": {
      "avg_title_similarity": null,
      "avg_date_gap_days": null
    },
    "confirmed_signals": {
      "avg_title_similarity": null,
      "avg_date_gap_days": null
    },
    "recommendation": "Insufficient data (0 reviews, need \u22655 for reliable stats)"
  },
  "driftWeights": {
    "org_id": "4adf3dd5-e58f-465f-89fa-e235f9b9e9eb",
    "source": "defaults",
    "density_weight": 0.45,
    "confidence_weight": 0.35,
    "volume_weight": 0.2,
    "factual_weight": 0.6,
    "semantic_weight": 0.4
  },
  "entities": [],
  "search": {
    "results": [
      {
        "chunk_id": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d_chunk_0",
        "document_id": "a8ec75b0-7def-4ef6-96fb-58d7a8b3166d",
        "document_title": "Urban Mobility Policy 2027 \u2014 Accelerated Electrification",
        "content": "The transit authority will require all public transit vehicles to transition to electric propulsion within 24 months. The transit authority will cap fleet maintenance downtime at 24 hours per vehicle per quarter. The transit authority will allocate 500 million dollars for eastern corridor infrastructure upgrades. The transit authority will expand the dedicated bus lane network to 250 kilometers. The transit authority will operate 4000 electric buses across the network. The transit authority will provide 6000 new park-and-ride parking spaces. The transit authority will run peak-hour service every 4 minutes. The transit authority will set the base passenger fare at 1 dollars per ride. The transit authority will install 1200 new bike-share docks. The transit authority will deploy 900 vehicle charging stations. The transit authority will retrofit 300 stations for full accessibility. The transit authority will reduce transit carbon emissions by 60 percent. The transit authority will operate weekend night service for 24 hours. The transit authority will provide an annual operating subsidy of 200 million dollars.",
        "score": 0.5667,
        "page": 0
      },
      {
        "chunk_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5_chunk_0",
        "document_id": "0ef6f580-c012-47e3-ba22-0c157b6e08a5",
        "document_title": "Urban Mobility Policy (Revised) \u2014 Fiscal Restraint",
        "content": "The transit authority will require all public transit vehicles to transition to electric propulsion within 96 months. The transit authority will cap fleet maintenance downtime at 96 hours per vehicle per quarter. The transit authority will allocate 180 million dollars for eastern corridor infrastructure upgrades. The transit authority will expand the dedicated bus lane network to 50 kilometers. The transit authority will operate 1500 electric buses across the network. The transit authority will provide 1000 new park-and-ride parking spaces. The transit authority will run peak-hour service every 15 minutes. The transit authority will set the base passenger fare at 5 dollars per ride. The transit authority will install 200 new bike-share docks. The transit authority will deploy 150 vehicle charging stations. The transit authority will retrofit 60 stations for full accessibility. The transit authority will reduce transit carbon emissions by 10 percent. The transit authority will operate weekend night service for 6 hours. The transit authority will provide an annual operating subsidy of 50 million dollars.",
        "score": 0.5655,
        "page": 0
      },
      {
        "chunk_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d_chunk_0",
        "document_id": "6c3f0589-8a8a-4a0b-a47d-3de933c2570d",
        "document_title": "Urban Mobility Policy \u2014 Interim Compromise",
        "content": "The transit authority will require all public transit vehicles to transition to electric propulsion within 60 months. The transit authority will cap fleet maintenance downtime at 60 hours per vehicle per quarter. The transit authority will allocate 320 million dollars for eastern corridor infrastructure upgrades. The transit authority will expand the dedicated bus lane network to 150 kilometers. The transit authority will operate 2800 electric buses across the network. The transit authority will provide 3500 new park-and-ride parking spaces. The transit authority will run peak-hour service every 9 minutes. The transit authority will set the base passenger fare at 3 dollars per ride. The transit authority will install 700 new bike-share docks. The transit authority will deploy 500 vehicle charging stations. The transit authority will retrofit 180 stations for full accessibility. The transit authority will reduce transit carbon emissions by 35 percent. The transit authority will operate weekend night service for 16 hours. The transit authority will provide an annual operating subsidy of 120 million dollars.",
        "score": 0.5541,
        "page": 0
      }
    ],
    "query": "electric buses fleet",
    "total": 3
  }
} as const;
